### ISSUE TITLE
import snack

### ISSUE THREAD

**Issue by geekhenno** [arnemolland/snack#1]
the snack bar already exists in the material I can not use your package because has the same name

**Comment by arnemolland** [comment]
Hi @hennonoman!

This package only contains extensions on the SnackBar class from the Material library. Just create a regular/material `SnackBar`, import the `snack` package and use the `.show(context)` extension.

Example:
```dart
class Example extends StatelessWidget {
  final bar = SnackBar(content: Text('Hello, world!'));
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: RaisedButton(
        child: Text('Show snack'),
        onPressed: () => bar.show(context),
      ),
    );
  }
}
```

**Comment by geekhenno** [comment]
thank you so much, it works
